[tool.ruff]
target-version = "py310"
line-length = 99
extend-exclude = [
    ".DS_Store",
    ".pytest_cache",
    "__pycache__",
]

[tool.ruff.lint]
ignore = [
    "E701"
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "F401",  # `foo` imported but unused
]
